// import { Person } from "./TS"
export type Person = {
  id: number
  name: string
  brand: string
  price: string
  quantity: number
  total: number
  status: number
  updated: number
}

export const data: Person[] = [
  {
    id: 1,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 2,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 1,
    updated: 0,
  },
  {
    id: 3,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 2,
    updated: 0,
  },
  {
    id: 4,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 3,
    updated: 0,
  },
  {
    id: 5,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 6,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 7,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 8,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 9,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
  {
    id: 10,
    name: "Checken Brest freast, boneless mutta marmiriden",
    brand: "Hormel black Lablemy",
    price: "$ 60.07 / 6*1LB",
    quantity: 6,
    total: 92399,
    status: 0,
    updated: 0,
  },
]

//50 us states array
export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
]
